# Generated by Django 3.0.5 on 2020-04-10 15:07

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='thanhpho',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100, verbose_name='Thành phố')),
                ('slug', models.SlugField(max_length=255)),
            ],
            options={
                'verbose_name_plural': 'Thành phố',
            },
        ),
        migrations.CreateModel(
            name='quan_huyen',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100, verbose_name='Quận huyện')),
                ('slug', models.SlugField(max_length=255)),
                ('thanhphos', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='thanhpho.thanhpho', verbose_name='Thành phố')),
            ],
            options={
                'verbose_name_plural': 'Quận huyện',
            },
        ),
    ]
