# Generated by Django 3.0.5 on 2020-04-16 16:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('thanhpho', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='quan_huyen',
            name='thanhphos',
        ),
        migrations.AddField(
            model_name='thanhpho',
            name='quan_huyen',
            field=models.ManyToManyField(to='thanhpho.quan_huyen', verbose_name='Quận huyện'),
        ),
    ]
