# Generated by Django 3.0.5 on 2020-04-18 10:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sanpham', '0002_auto_20200416_1447'),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='action',
            field=models.BooleanField(default=False, verbose_name='Hiện thị ngoài trang chủ'),
        ),
        migrations.AddField(
            model_name='category',
            name='icon',
            field=models.ImageField(default='static/images/Real-Estate.png', upload_to='icon/', verbose_name='Icon'),
        ),
    ]
