# Generated by Django 3.0.5 on 2020-05-29 09:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sanpham', '0004_auto_20200418_1833'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='luotxem',
            field=models.IntegerField(default=1),
        ),
    ]
