# Generated by Django 3.0.5 on 2020-06-02 17:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('sanpham', '0006_post_luutin'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='post',
            name='luutin',
        ),
    ]
