# Generated by Django 3.0.5 on 2020-06-02 17:52

import ckeditor.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='baiviet',
            name='mota',
            field=ckeditor.fields.RichTextField(null=True, verbose_name='Mô tả'),
        ),
    ]
