# Generated by Django 3.0.5 on 2020-04-13 14:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('taikhoan', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='DiaChi',
            field=models.TextField(default='', null=True, verbose_name='Địa chỉ'),
        ),
    ]
