# Generated by Django 3.0.5 on 2020-04-13 16:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('taikhoan', '0002_auto_20200413_2142'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='avatar',
            field=models.ImageField(default='static/images/aditya.png', null=True, upload_to='media/avatar/%Y/%m/%d/', verbose_name='Hình đại diện'),
        ),
    ]
