# Generated by Django 3.0.5 on 2020-04-15 18:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('taikhoan', '0004_lever_package'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='package',
            options={'verbose_name_plural': 'Gói vip'},
        ),
        migrations.RemoveField(
            model_name='package',
            name='thoi_gian',
        ),
    ]
