# Generated by Django 3.0.5 on 2020-04-15 18:05

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('taikhoan', '0005_auto_20200416_0101'),
    ]

    operations = [
        migrations.CreateModel(
            name='Vip',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('thoigian', models.DateTimeField(blank=True, null=True, verbose_name='Chọn thời gian kết thúc')),
                ('package', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='taikhoan.package', verbose_name='Chọn gói vip')),
                ('taikhoan', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name_plural': 'Đăng kí Vip',
            },
        ),
        migrations.DeleteModel(
            name='Lever',
        ),
    ]
