# Generated by Django 3.0.5 on 2020-04-15 18:24

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('taikhoan', '0006_auto_20200416_0105'),
    ]

    operations = [
        migrations.AddField(
            model_name='vip',
            name='kiemtra',
            field=models.BooleanField(default=False, verbose_name='Trạng thái'),
        ),
        migrations.AddField(
            model_name='vip',
            name='ngaytao',
            field=models.DateTimeField(auto_created=True, auto_now_add=True, default=django.utils.timezone.now, verbose_name='Ngày tạo'),
            preserve_default=False,
        ),
    ]
