# Generated by Django 3.0.5 on 2020-04-18 11:33

import ckeditor.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Slider',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=50)),
                ('mota', ckeditor.fields.RichTextField(max_length=1000, null=True, verbose_name='Nội dung ')),
                ('hinh', models.ImageField(null=True, upload_to='slider/', verbose_name='Hình slider')),
                ('action', models.BooleanField(default=False, verbose_name='Hiện thị ngoài trang chủ')),
            ],
            options={
                'verbose_name_plural': 'Banner ',
            },
        ),
        migrations.CreateModel(
            name='Ykienkhach',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('mota', ckeditor.fields.RichTextField(max_length=1000, null=True, verbose_name='Nội dung ')),
                ('fb', models.CharField(default='https://fb.com/#', max_length=90, null=True, verbose_name='Link face')),
                ('tw', models.CharField(default='https://fb.com/#', max_length=90, null=True, verbose_name='Link twitter')),
                ('linkedin', models.CharField(default='https://fb.com/#', max_length=90, null=True, verbose_name='linkedin')),
                ('email', models.CharField(default='https://fb.com/#', max_length=90, null=True, verbose_name='email')),
                ('hinh', models.ImageField(null=True, upload_to='khach-hang/', verbose_name='Hình đại diện')),
                ('action', models.BooleanField(default=False, verbose_name='Hiện thị ngoài trang chủ')),
            ],
            options={
                'verbose_name_plural': 'Ý kiến khách hàng ',
            },
        ),
    ]
