# Generated by Django 3.0.5 on 2020-04-18 12:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='slider',
            name='thutu',
            field=models.CharField(choices=[('1', 'Đầu tiên'), ('2', 'Thứ 2'), ('3', 'Thứ 3'), ('4', 'Thứ n')], default='2', max_length=20, verbose_name='Chọn thứ tự hiện thị'),
        ),
    ]
