# Generated by Django 3.0.5 on 2020-05-08 15:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0002_slider_thutu'),
    ]

    operations = [
        migrations.AlterField(
            model_name='slider',
            name='thutu',
            field=models.CharField(choices=[('1', 'Đầu tiên'), ('2', 'Thứ 2'), ('3', 'Thứ 3'), ('4', 'Thứ 4'), ('5', 'Thứ 5'), ('6', 'Thứ 6'), ('7', 'Thứ 7')], default='2', max_length=20, unique=True, verbose_name='Chọn thứ tự hiện thị'),
        ),
        migrations.AlterField(
            model_name='slider',
            name='title',
            field=models.CharField(max_length=50, unique=True),
        ),
        migrations.AlterField(
            model_name='ykienkhach',
            name='email',
            field=models.CharField(default='abc@gmail.com', max_length=90, null=True, verbose_name='email'),
        ),
    ]
